name: flutter_training
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.2.0
  flutter_svg: ^2.0.1
  hooks_riverpod: ^2.2.0
  riverpod_annotation: ^1.2.1
  yumemi_weather:
    path: packages/yumemi_weather

dev_dependencies:
  blendthink_lints: ^3.0.0
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  flutter_test:
    sdk: flutter

  pedantic_mono: ^1.21.1
  riverpod_generator: ^1.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
